title: "Galen's Pacific Crest Trail Tracker"
description: "Map, progress, short updates & photos from the trail"
url: ""  # GitHub Pages sets this
baseurl: "/hike-tracker"  # set to "/REPO_NAME" if needed
markdown: kramdown
theme: null
permalink: pretty
